# Generated by Django 5.2.1 on 2026-06-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('nickname', models.CharField(max_length=50, verbose_name='닉네임')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='프로필 이미지')),
                ('kakao_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='카카오 아이디')),
                ('is_active', models.BooleanField(default=True, verbose_name='계정 활성화 여부')),
                ('is_staff', models.BooleanField(default=False, verbose_name='admin 여부')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'ordering': ['-created_at'],
            },
        ),
    ]
