# Generated by Django 5.2.1 on 2026-06-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('wine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_wines',
            field=models.ManyToManyField(blank=True, related_name='favorite_users', to='wine.wine'),
        ),
    ]
