# Generated by Django 5.2.1 on 2026-06-07 23:32

import django.core.validators
import django.db.models.deletion
import wine.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eng_name', models.CharField(max_length=255, verbose_name='영어 이름')),
                ('kor_name', models.CharField(max_length=255, verbose_name='한국어 이름')),
            ],
            options={
                'verbose_name': '국가',
                'verbose_name_plural': '국가',
                'ordering': ['kor_name'],
            },
        ),
        migrations.CreateModel(
            name='GrapeVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eng_name', models.CharField(max_length=255, verbose_name='영어 이름')),
                ('kor_name', models.CharField(max_length=255, verbose_name='한국어 이름')),
            ],
            options={
                'verbose_name': '품종',
                'verbose_name_plural': '품종',
                'ordering': ['kor_name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('fruity', '과일 (Fruity)'), ('floral', '꽃 (Floral)'), ('oaky', '오크 (Oaky)'), ('vegetal', '식물 (Vegetal)')], max_length=50, verbose_name='카테고리')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='이름')),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eng_name', models.CharField(max_length=255, verbose_name='영어 이름')),
                ('kor_name', models.CharField(max_length=255, verbose_name='한국어 이름')),
                ('type', models.CharField(choices=[('red', '레드 (Red)'), ('white', '화이트 (White)'), ('sparkling', '스파클링 (Sparkling)'), ('rose', '로즈 (Rose)')], max_length=50, verbose_name='타입')),
                ('image', models.ImageField(blank=True, null=True, upload_to='wines/', verbose_name='와인 이미지')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wines', to='wine.country')),
                ('grape_varieties', models.ManyToManyField(blank=True, related_name='wines', to='wine.grapevariety')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_wines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '와인',
                'verbose_name_plural': '와인',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WineReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='리뷰 내용')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50), wine.models.validate_multiple_of_five], verbose_name='평점')),
                ('body', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='바디')),
                ('acidity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='산도')),
                ('sweetness', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='당도')),
                ('tannin', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='탄닌')),
                ('is_public', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_reviews', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='reviews', to='wine.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wine_reviews', to=settings.AUTH_USER_MODEL)),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='wine.wine')),
            ],
            options={
                'verbose_name': '와인 리뷰',
                'verbose_name_plural': '와인 리뷰',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WineReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='review_images/', verbose_name='이미지')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wine.winereview')),
            ],
            options={
                'verbose_name': '리뷰 이미지',
                'verbose_name_plural': '리뷰 이미지',
                'ordering': ['created_at'],
            },
        ),
    ]
