# Generated by Django 5.2.1 on 2026-07-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='type',
            field=models.CharField(blank=True, choices=[('red', '레드 (Red)'), ('white', '화이트 (White)'), ('sparkling', '스파클링 (Sparkling)'), ('rose', '로즈 (Rose)')], default='', max_length=50, verbose_name='타입'),
        ),
    ]
