# Generated by Django 5.2.1 on 2026-07-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0002_alter_wine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='image_url',
            field=models.URLField(blank=True, default='', verbose_name='외부 이미지 URL'),
        ),
    ]
