# Generated by Django 5.2.1 on 2026-07-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0003_wine_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='bubble_avg_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='버블 평균 평점'),
        ),
    ]
